# Generated by Django 5.2.9 on 2025-12-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='dob',
            new_name='date_of_joining',
        ),
        migrations.AddField(
            model_name='employees',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='shift_end',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='employees',
            name='shift_start',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
